apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: log-monitoring
spec:
  version: 8.8.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: log-monitoring