spring:
  application:
    name: simple-rest-api

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  datasource:
    url: jdbc:mysql://simple-rest-api.c3qu1hehhhiv.us-east-1.rds.amazonaws.com:3306/myuser
    username: simplerestuser
    password: simplerestapipassword
    driver-class-name: com.mysql.cj.jdbc.Driver

# https://www.baeldung.com/spring-boot-actuators
management:
  endpoints:
    web:
      exposure:
        include: health, metric, info, prometheus
  endpoint:
    health:
      show-details: always